#Product module
product.fetchingAndPaging=SELECT product_id, name, description, brand, category_id, status, created_at, updated_at \
FROM products \
WHERE LOWER(name) LIKE LOWER(?) \
ORDER BY created_at DESC \
LIMIT ? OFFSET ?
product.countByName=SELECT COUNT(*) FROM products WHERE name LIKE ?